name: .NET

on:
  push:
    branches: [ main, dev, feature1/*, fix/*, release/* ]

  pull_request:
    branches: [ main ]

  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            9.0.x

    # Create Local NuGet Source

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    # Endpoint.Contract

    - name: Restore Endpoint.Contract
      run: dotnet restore ./src/*/*/Endpoint.Contract.csproj

    - name: Build Endpoint.Contract
      run: dotnet build ./src/*/*/Endpoint.Contract.csproj --no-restore  -c Release

    - name: Pack Endpoint.Contract
      run: dotnet pack ./src/*/*/Endpoint.Contract.csproj --no-restore -o ~/nuget  -c Release

    # Endpoint.Core.Generator

    - name: Restore Endpoint.Core.Generator
      run: dotnet restore ./src/*/*/Endpoint.Core.Generator.csproj

    - name: Build Endpoint.Core.Generator
      run: dotnet build ./src/*/*/Endpoint.Core.Generator.csproj --no-restore  -c Release

    - name: Pack Endpoint.Core.Generator
      run: dotnet pack ./src/*/*/Endpoint.Core.Generator.csproj --no-restore -o ~/nuget  -c Release

    # Endpoint.Core

    - name: Restore Endpoint.Core
      run: dotnet restore ./src/*/*/Endpoint.Core.csproj

    - name: Build Endpoint.Core
      run: dotnet build ./src/*/*/Endpoint.Core.csproj --no-restore  -c Release

    - name: Pack Endpoint.Core
      run: dotnet pack ./src/*/*/Endpoint.Core.csproj --no-restore -o ~/nuget  -c Release

    # Endpoint.AspNetCore.Generator

    - name: Restore Endpoint.AspNetCore.Generator
      run: dotnet restore ./src/*/*/Endpoint.AspNetCore.Generator.csproj

    - name: Build Endpoint.AspNetCore.Generator
      run: dotnet build ./src/*/*/Endpoint.AspNetCore.Generator.csproj --no-restore  -c Release

    - name: Pack Endpoint.AspNetCore.Generator
      run: dotnet pack ./src/*/*/Endpoint.AspNetCore.Generator.csproj --no-restore -o ~/nuget  -c Release

    # Endpoint.AspNetCore

    - name: Restore Endpoint.AspNetCore
      run: dotnet restore ./src/*/*/Endpoint.AspNetCore.csproj

    - name: Build Endpoint.AspNetCore
      run: dotnet build ./src/*/*/Endpoint.AspNetCore.csproj --no-restore  -c Release

    - name: Pack Endpoint.AspNetCore
      run: dotnet pack ./src/*/*/Endpoint.AspNetCore.csproj --no-restore -o ~/nuget  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.event_name == 'release' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s https://api.nuget.org/v3/index.json
        -k ${{ secrets.NuGetSourcePassword }}
        --skip-duplicate
